/** Stable machine codes for frontend-thrown errors (client guards + auth UI). */
export const FRONTEND_ERROR_CODES = {
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_MFA_UNSUPPORTED: 'AUTH_MFA_UNSUPPORTED',
  AUTH_OAUTH_NO_REDIRECT: 'AUTH_OAUTH_NO_REDIRECT',
  AUTH_PASSKEY_CANCELLED: 'AUTH_PASSKEY_CANCELLED',
  AUTH_PASSKEY_UNAVAILABLE: 'AUTH_PASSKEY_UNAVAILABLE',
  INVITE_INVALID_OR_EXPIRED: 'INVITE_INVALID_OR_EXPIRED',
  MEMBER_ROLE_REQUIRED: 'MEMBER_ROLE_REQUIRED',
} as const;
