import { I18N_NAMESPACES } from '@/lib/i18n/namespaces.ts';

/** Appearance panel copy lives in `common` beside the locale/date/money cards it hosts. */
export const APPEARANCE_NS = I18N_NAMESPACES.common;

/**
 * Key paths for the Appearance panel's own chrome. Option *values* (accent
 * names, font families, radius names) stay in `shared/theme/presets.ts` — they
 * are product nomenclature, and font families are proper nouns that must not be
 * translated.
 */
export const APPEARANCE_KEYS = {
  themeTitle: 'appearance.themeTitle',
  themeLocked: 'appearance.themeLocked',
  themeDescription: 'appearance.themeDescription',
  presetAria: 'appearance.presetAria',
  copyLink: 'appearance.copyLink',
  shuffleHint: 'appearance.shuffleHint',
  codeLabel: 'appearance.codeLabel',
  codePlaceholder: 'appearance.codePlaceholder',
  apply: 'appearance.apply',
  pickAnyColour: 'appearance.pickAnyColour',
  modeTitle: 'appearance.modeTitle',
  modeDescription: 'appearance.modeDescription',
  colourTitle: 'appearance.colourTitle',
  colourDescription: 'appearance.colourDescription',
  accentColour: 'appearance.accentColour',
  chartColour: 'appearance.chartColour',
  baseColour: 'appearance.baseColour',
  harmony: 'appearance.harmony',
  harmonyAria: 'appearance.harmonyAria',
  accentIntensity: 'appearance.accentIntensity',
  typeTitle: 'appearance.typeTitle',
  typeDescription: 'appearance.typeDescription',
  bodyFont: 'appearance.bodyFont',
  headingFont: 'appearance.headingFont',
  radius: 'appearance.radius',
  shapeLanguage: 'appearance.shapeLanguage',
  typeScale: 'appearance.typeScale',
  menu: 'appearance.menu',
  menuAria: 'appearance.menuAria',
  iconsTitle: 'appearance.iconsTitle',
  iconsDescription: 'appearance.iconsDescription',
  iconWeight: 'appearance.iconWeight',
  iconColour: 'appearance.iconColour',
  iconLibrary: 'appearance.iconLibrary',
  layoutTitle: 'appearance.layoutTitle',
  layoutDescription: 'appearance.layoutDescription',
  contentWidth: 'appearance.contentWidth',
  surfaceTitle: 'appearance.surfaceTitle',
  surfaceDescription: 'appearance.surfaceDescription',
  density: 'appearance.density',
  contrast: 'appearance.contrast',
  elevation: 'appearance.elevation',
  separation: 'appearance.separation',
  separationAria: 'appearance.separationAria',
  motion: 'appearance.motion',
  focusRing: 'appearance.focusRing',
  notificationsTitle: 'appearance.notificationsTitle',
  notificationsDescription: 'appearance.notificationsDescription',
  toastDesign: 'appearance.toastDesign',
  position: 'appearance.position',
  positionAria: 'appearance.positionAria',
  previewSuccess: 'appearance.previewSuccess',
  previewError: 'appearance.previewError',
  previewWarning: 'appearance.previewWarning',
  previewInfo: 'appearance.previewInfo',
  shuffleSection: 'appearance.shuffleSection',
  sectionColour: 'appearance.sectionColour',
  sectionType: 'appearance.sectionType',
  sectionSurface: 'appearance.sectionSurface',
  sectionNotifications: 'appearance.sectionNotifications',
  custom: 'appearance.custom',
  customWith: 'appearance.customWith',
} as const;
